### ISSUE TITLE
Using Exim to input for Xterm

### ISSUE THREAD

**Issue by bvraghav** [ch11ng/exim#1]
I am looking for using the icy-mode for minor completions in my xterm. This is the direction I choose to look forward, as the program I am using is a 3D modeling software called BRL CAD, which is primarily a commandline interface to Constructive Solid Geometry editing.

This uses an OGL-based X-window to render the commands I choose, and makes use of the 4-cores to render using parallel processing when required. I am pretty sure, I do not need the unicode input, which is apparently the best use case for this library.

In such a case, is EXWM  a good choice? If not, will EXIM be useful to fulfill what I am seeking?

I don't know if this is the right place to ask this question. But please suggest an alternate way.

**Comment by ch11ng** [comment]
I think it's worth a try, but you have to wrap icy-mode as an input method first.  Basically EXIM just invokes `input-method-function` and passes the result to the X window; it does not care about how the result is generated.  If you have no experience with input methods, please try some builtin methods ("TeX" for example) first.

**Comment by ch11ng** [comment]
Hi, I've merged this repo into EXWM.  So I'm closing this issue now.
