### ISSUE TITLE
How can I detect the exim is working?

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exim#3]
I need a function or a variable to  test  current input area is a emacs buffer or a x window's input box, any suggestion?

**Comment by ch11ng** [comment]
This can't be done easily.  You need to use `xcb:GetInputFocus` perhaps.  Emacs's `focus-in-hook` and `focus-out-hook` may also help.

**Comment by tumashu** [comment]
I find a simple way which can solve my own problem:

```
(string= (buffer-name) " *temp*")
```
