### ISSUE TITLE
 <Multi_key> is undefined

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exim#4]
I set the right control key on my keyboard as compose key, but when that key is
pressed, I get this error.

    <Multi_key> is undefined

The issue is discussed here:
http://emacs.stackexchange.com/questions/3650/compose-key-in-emacs-multi-key-is-undefined
and the solution is to run emacs with XMODIFIERS set to @im=none:

    export XMODIFIERS=@im=none 

is there a way to solve it within exim?

**Comment by ch11ng** [comment]
It seems it's a bug in Emacs that prevents compose key and XIM from working at the same time.  It should be fixed in Emacs instead.

**Comment by QiangF** [comment]
OK. I will upgrade to debian stretch once it is released.
